apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-app-chart.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "test-app-chart.name" . }}
    helm.sh/chart: {{ include "test-app-chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "test-app-chart.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        "consul.hashicorp.com/connect-service-upstreams": "couchdb:5984"
        "consul.hashicorp.com/connect-inject": "true"
      labels:
        app.kubernetes.io/name: {{ include "test-app-chart.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccount: {{ include "test-app-chart.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - curl
              - http://localhost:8080/_up
          readinessProbe:
            exec:
              command:
              - curl
              - http://localhost:8080/_ready
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"